[package]
name = "fs_pro_macros"
version = "1.0.0"
authors = ["AliBasicCoder <aliahmedreda34@gmail.com>"]
edition = "2018"
description = "a package used by fs_pro"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
regex = "1.0"
proc-macro-error = "1.0"